[package]
name = "janusgraph-cmd"
version = "0.0.0"
edition = "2018"

[dependencies]
grpc            = "~0.7"
grpc-protobuf   = "~0.7"
protobuf        = "~2"
futures         = "0.3.1"
structopt       = "0.3.14"

[build-dependencies]
protoc-rust-grpc = "0.7.0"
